name: flutter_toolbar
description: A flutter package which display the library is a library with dynamic toolbars and beautiful animation ...
version: 0.0.2
repository: https://github.com/ThuyenPV/flutter_toolbar
issue_tracker: https://github.com/ThuyenPV/flutter_toolbar/issues
homepage: https://github.com/ThuyenPV/flutter_toolbar

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
